import process from 'node:process'

import { defineConfig } from 'oxlint'

import type { OxlintConfig } from './oxlint.ts'
import { getInstalledPackages } from './utils.ts'

const TAILWIND_PLUGIN = 'oxlint-tailwindcss'

interface TailwindOptions {
  /**
   * Path to the Tailwind entry CSS, so the plugin can resolve class names.
   * Required. In a monorepo, pass an array of glob → CSS mappings; the last
   * matching entry wins, so end with a `'**'` catch-all.
   *
   * @example 'src/global.css'
   * @example
   * ```ts
   * [
   *   { files: 'packages/ui/**', use: 'packages/ui/src/styles.css' },
   *   { files: '**', use: 'src/global.css' },
   * ]
   * ```
   */
  entryPoint: string | { files: string; use: string }[]
  /**
   * Class names to exempt from `no-unknown-classes` — e.g. classes generated by
   * component libraries that the plugin can't resolve from the entry CSS.
   */
  ignoreClasses?: string[]
  /**
   * Directory scanned to check the plugin is installed.
   *
   * @default process.cwd()
   */
  cwd?: string
}

/**
 * Tailwind v4 linting via [`oxlint-tailwindcss`](https://github.com/sergioazoc/oxlint-tailwindcss),
 * an optional peer dependency — throws if it is not installed.
 */
export function tailwindConfig({
  entryPoint,
  ignoreClasses = [],
  cwd = process.cwd(),
}: TailwindOptions): OxlintConfig {
  if (!getInstalledPackages(cwd).has(TAILWIND_PLUGIN)) {
    throw new Error(
      `[@letstri/oxlint-config] Tailwind linting needs "${TAILWIND_PLUGIN}". ` +
        `Install it: pnpm add -D ${TAILWIND_PLUGIN}`,
    )
  }

  return defineConfig({
    jsPlugins: [TAILWIND_PLUGIN],
    settings: { tailwindcss: { entryPoint } },
    rules: {
      'tailwindcss/enforce-sort-order': 'error',
      'tailwindcss/enforce-consistent-line-wrapping': 'off',
      'tailwindcss/enforce-canonical': 'error',
      'tailwindcss/consistent-variant-order': 'error',
      'tailwindcss/enforce-consistent-important-position': 'error',
      'tailwindcss/no-conflicting-classes': 'error',
      'tailwindcss/no-deprecated-classes': 'error',
      'tailwindcss/no-duplicate-classes': 'error',
      'tailwindcss/no-unnecessary-arbitrary-value': 'warn',
      'tailwindcss/no-unknown-classes': ['error', { allowlist: ignoreClasses }],
    },
  })
}
